name: Auto Pack and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Stage files into installer layout
        run: |
	@@ -37,16 +35,3 @@ jobs:
          files: PriconneRe-VN-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog Content
        shell: pwsh
        run: |
          ./.github/scripts/make_changelog.ps1
      - name: Write Notes to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $ChangelogText = Get-Content ./RELEASE_NOTE -Raw
          gh release edit ${{ github.ref_name }} --notes "$ChangelogText"