name: Auto Pack and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Stage files into installer layout
        run: |
          mkdir -p staging/BepInEx/Translation/vi
          cp -r Text staging/BepInEx/Translation/vi/Text

      - name: Stamp version into Version.txt
        run: |
          TAG_NAME=${{ github.ref_name }}
          sed -i "s/Pre-release/$TAG_NAME/g" staging/BepInEx/Translation/vi/Text/Version.txt

      - name: Archive translation files to zip
        run: |
          cd staging
          zip -r ../PriconneRe-VN-${{ github.ref_name }}.zip BepInEx

      - name: Upload asset to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: PriconneRe-VN-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog Content
        shell: pwsh
        run: |
          ./.github/scripts/make_changelog.ps1

      - name: Write Notes to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $ChangelogText = Get-Content ./RELEASE_NOTE -Raw
          gh release edit ${{ github.ref_name }} --notes "$ChangelogText"
